name: flutter_liff
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.6.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.11.0
  flutter:
    sdk: flutter

  geoflutterfire_plus: ^0.0.10
  google_maps_flutter: ^2.2.6
  google_maps_flutter_web: ^0.4.0+8
  pedantic_mono: ^1.21.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
